export const ROLES = {
  SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
  ADMIN: 'ROLE_ADMIN',
  USER: 'ROLE_USER',
} as const;

export const SECTION_TYPES = {
  HERO_BANNER: 'HERO_BANNER',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  INFO_BLOCK: 'INFO_BLOCK',
  RICH_TEXT: 'RICH_TEXT',
  IMAGE_CARD: 'IMAGE_CARD',
  PROMOTION_BANNER: 'PROMOTION_BANNER',
} as const;

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
